package com.example.antserver.fake

import com.example.antserver.domain.schedule.Schedule
import com.example.antserver.domain.schedule.ScheduleRepository

class FakeScheduleRepository: ScheduleRepository {

    private var autoGeneratedId = 0L
     val data: MutableList<Schedule> = mutableListOf()

    override fun save(schedule: Schedule): Schedule {
        val existingIndex = data.indexOfFirst { it.id == schedule.id }

        return if (existingIndex != -1) {
            data[existingIndex] = schedule
            schedule
        } else {
            val newParticipation = schedule.copy(id = ++autoGeneratedId)
            data.add(newParticipation)
            newParticipation
        }
    }

    override fun saveAll(schedules: List<Schedule>): List<Schedule> {
        return schedules.map { save(it) }
    }

    override fun findById(id: Long): Schedule? {
        return data.find { it.id == id }
    }

    override fun findAllById(ids: List<Long>): List<Schedule> {
        return data.filter { it.id in ids }
    }

    override fun findAllByPollId(pollId: Long): List<Schedule> {
        return data.filter { it.pollId == pollId }
    }

    fun clear() {
        autoGeneratedId = 0L
        data.clear()
    }
}