package com.example.antserver.fake

import com.example.antserver.domain.participation.Participation
import com.example.antserver.domain.poll.Poll
import com.example.antserver.domain.poll.PollRepository
import com.example.antserver.domain.poll.PollStatus
import org.springframework.data.domain.Page
import org.springframework.data.domain.PageImpl
import org.springframework.data.domain.Pageable

class FakePollRepository: PollRepository {
    private var autoGeneratedId = 0L
    private val data: MutableList<Poll> = mutableListOf()

    override fun save(poll: Poll): Poll {
        val existingIndex = data.indexOfFirst { it.id == poll.id }

        return if (existingIndex != -1) {
            data[existingIndex] = poll
            poll
        } else {
            val newPoll = poll.copy(id = ++autoGeneratedId)
            data.add(newPoll)
            newPoll
        }
    }

    override fun findById(id: Long): Poll? {
        return data.find { it.id == id }
    }

    override fun findAllByPollStatus(status: PollStatus, pageable: Pageable): Page<Poll> {
        val filteredPolls = data.filter { it.pollStatus == status }
        val start = pageable.offset.toInt()
        val end = (start + pageable.pageSize).coerceAtMost(filteredPolls.size)

        return PageImpl(filteredPolls.subList(start, end), pageable, filteredPolls.size.toLong())
    }

    override fun findLast(): Poll? {
        return data.maxByOrNull { it.createdAt!! }
    }

    fun clear() {
        autoGeneratedId = 0L
        data.clear()
    }
}