package com.example.antserver.fake

import com.example.antserver.domain.participation.Participation
import com.example.antserver.domain.participation.ParticipationRepository
import java.util.*

class FakeParticipationRepository: ParticipationRepository {
    private var autoGeneratedId = 0L
    private val data: MutableList<Participation> = mutableListOf()

    override fun save(participation: Participation): Participation {
        val existingIndex = data.indexOfFirst { it.id == participation.id }

        return if (existingIndex != -1) {
            data[existingIndex] = participation
            participation
        } else {
            val newParticipation = participation.copy(id = ++autoGeneratedId)
            data.add(newParticipation)
            newParticipation
        }
    }

    override fun saveAll(participations: List<Participation>): List<Participation> {
        return participations.map { save(it) }
    }

    override fun findAllByUserId(userId: UUID): List<Participation> {
        return data.filter { it.userId == userId }
    }

    fun clear() {
        autoGeneratedId = 0L
        data.clear()
    }
}